baseURL = "https://gorden.bangunan.co/"
languageCode = "id"
title = "Pasang Gorden | Jual dan Jasa Pasang Gorden Berpengalaman"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Jual Gorden dan Jasa Pasang Gorden - Berpengalaman, Profesional, dan Berkualitas dengan harga yang terjangkau"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jasa pasang gorden", "gorden rumah", "tukang pasang gorden berpengalaman", "gorden interior", "gorden ruang tamu", "gorden kamar tidur"]
  base_price = 85000
  price_range = 800000
  free_consultation = true
  service_types = [
  "Pasang Gorden Interior",
  "Pasang Gorden Custom",
  "Pasang Gorden Anti Panas",
  "Pasang Gorden Kamar Tidur",
  "Pasang Gorden Ruang Tamu"
  ]
  categories = ["Jasa Gorden", "Tukang Pasang Gorden", "Gorden Interior"]
  payment_methods = ["Bayar Bertahap", "Transfer Bank", "Bayar DP 50%", "Transfer Setelah Selesai"]
  cancellation_policies = [
  "Layanan dapat dibatalkan jika tidak sesuai dengan kesepakatan.",
  "Pengembalian biaya jika hasil tidak memuaskan.",
  "Revisi gratis jika hasil pemasangan tidak rapih."
  ]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Subang", "Cikampek", "Purwakarta", "Rangkas Bitung", "Serang"]
  service_output = "Ruangan dengan gorden yang terpasang rapih sesuai permintaan"

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Jasa Pasang Gorden Profesional"
  hero_description = "Kami menawarkan berbagai pilihan gorden berkualitas, dengan desain elegan dan material tahan lama. Solusi terbaik untuk mempercantik interior rumah atau kantor Anda dengan pemasangan yang rapi dan berpengalaman."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Gorden"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan layanan pasang gorden profesional dengan berbagai pilihan desain, bahan berkualitas, dan harga terjangkau. Layanan pengukuran dan konsultasi gratis juga tersedia untuk membantu Anda menemukan pilihan gorden terbaik."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "Gorden.bangunan.co menawarkan berbagai pilihan gorden berkualitas dengan desain elegan dan material yang tahan lama. Kami mengutamakan kepuasan pelanggan dengan pemasangan gorden yang rapi, cepat, dan profesional. Pilih kami untuk mempercantik rumah atau kantor Anda dengan gorden yang fungsional dan estetis."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Rudi|Hendra|Agus|Wawan|Fajar|Rio}"
  message = "{Saya memasang gorden dari gorden.bangunan.co di rumah saya, dan hasilnya {sangat memuaskan|luar biasa}. Kualitasnya {bagus|hebat} dan pemasangannya {rapi|cepat}.|Layanan dari gorden.bangunan.co sangat {bagus|memuaskan}, gorden yang saya pasang {berkualitas tinggi|terbaik} dan pemasangannya {teratur|baik}.}"
  response = "{Terima kasih atas kepercayaannya! Kami senang dapat menyediakan gorden {berkualitas|terbaik} untuk rumah Anda.|Kami sangat menghargai kepercayaan Anda. Senang mendengar Anda puas dengan gorden kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Sari|Fitri|Lina|Diah|Maya|Nur}"
  message = "{gorden.bangunan.co {sangat membantu|memudahkan} dalam melengkapi dekorasi rumah saya. Gorden yang saya pilih {sangat berkualitas|hebat} dan {cocok|pas} dengan desain interior saya.|Saya {sangat puas|senang} dengan layanan dari gorden.bangunan.co. Gorden yang saya pilih {sesuai|tepat} dengan gaya desain interior rumah saya.}"
  response = "{Kami sangat menghargai ulasan Anda. Senang mendengar bahwa Anda puas dengan layanan dan produk gorden kami.|Terima kasih atas ulasan positifnya. Kami senang dapat memenuhi kebutuhan gorden rumah Anda!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Agus|Bayu|Galih|Rizal|Bambang|Faisal|Ali|Toni|Deni}"
  message = "{Gorden dari gorden.bangunan.co {sangat elegan|indah} dan cocok untuk ruang tamu saya. Proses pemasangan juga {sangat cepat|efisien} dan {profesional|rapi}.|Layanan dari gorden.bangunan.co {cepat|efisien} dan hasilnya {elegan|hebat} untuk ruang tamu saya.}"
  response = "{Terima kasih! Kami berkomitmen untuk menyediakan gorden yang {fungsional|praktis} dan {estetis|elegan}.|Kami senang bisa bekerja sama dengan Anda. Terima kasih atas kepercayaannya!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Eko|Deni|Hendra|Toni|Wawan|Gilang|Ari|Benny|Yudi}"
  message = "{Saya {sangat puas|senang} dengan pemasangan gorden dari gorden.bangunan.co. Gorden tersebut {sangat sesuai|pas} dengan desain minimalis yang saya {inginkan|harapkan}.|Gorden dari gorden.bangunan.co {berkualitas|hebat}, dan pemasangannya {cepat|efisien} serta cocok dengan desain rumah saya.}"
  response = "{Senang mendengar Anda puas dengan produk dan layanan kami. Terima kasih atas kepercayaannya!|Kami sangat menghargai kepercayaan Anda. Terima kasih telah memilih layanan kami!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Dewi|Ayu|Sari|Fitri|Maya|Nur|Diah}"
  message = "{Pelayanan gorden.bangunan.co {sangat memuaskan|luar biasa}. Gorden yang saya {pasang|gunakan} di kantor sangat {berkualitas|bagus} dan sesuai dengan {harapan|ekspektasi} saya.|Saya {senang|puas} dengan layanan dari gorden.bangunan.co. Kualitas gordennya {sangat baik|hebat} dan pemasangannya {rapi|profesional}.}"
  response = "{Terima kasih! Kami senang dapat membantu mempercantik kantor Anda dengan gorden {terbaik|berkualitas}.|Kami sangat menghargai ulasan Anda. Terima kasih telah mempercayakan kebutuhan gorden Anda kepada kami!}"
  rating = 4.5

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Rio|Galih|Faisal|Yanto|Benny|Toni|Deni|Rizal|Wawan}"
  message = "{Gorden dari gorden.bangunan.co {sangat sesuai|tepat} dengan desain interior rumah saya. Pemasangannya juga {cepat|aman|rapi} dan gordennya {berkualitas tinggi|hebat}.|Saya {terkesan|puas} dengan layanan dari gorden.bangunan.co. Gorden yang saya pasang {berkualitas|kokoh} dan proses pemasangannya {cepat|efisien}.}"
  response = "{Kami senang mendengar bahwa Anda puas dengan produk dan pemasangan kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah mempercayakan pemasangan gorden Anda kepada kami. Kami senang hasilnya sesuai dengan harapan Anda.}"
  rating = 5

[[params.tabelItems]]
  name = "Pasang Gorden Kain Akrilik"
  price = "85.000/m"
[[params.tabelItems]]
  name = "Pasang Gorden Kain Katun"
  price = "15.000/m"
[[params.tabelItems]]
  name = "Pasang Gorden Kain Sutra"
  price = "9.000/m"
[[params.tabelItems]]
  name = "Pasang Gorden Kain Beludru"
  price = "75.000/m"
[[params.tabelItems]]
  name = "Pasang Gorden Kain Rayon"
  price = "17.500/m"
[[params.tabelItems]]
  name = "Pasang Gorden Kain Polyester"
  price = "35.000/m"
[[params.tabelItems]]
  name = "Pasang Gorden Kain Linen"
  price = "13.000/m"

[params.appliList]
  "Pasang Gorden Kain Akrilik" = "ruang tamu, kamar tidur, ruang keluarga"
  "Pasang Gorden Kain Katun" = "kamar tidur, ruang tamu, dapur"
  "Pasang Gorden Kain Sutra" = "ruang mewah, ruang tamu berkelas"
  "Pasang Gorden Kain Beludru" = "ruang keluarga, ruang tamu elegan"
  "Pasang Gorden Kain Rayon" = "ruang tidur, kamar mandi, ruang keluarga"
  "Pasang Gorden Kain Polyester" = "ruang kerja, dapur, ruang keluarga"
  "Pasang Gorden Kain Linen" = "ruang keluarga, ruang tamu"

[params.kegunaanList]
  "Pasang Gorden Kain Akrilik" = "memberikan tampilan elegan dan tahan lama"
  "Pasang Gorden Kain Katun" = "memberikan kesan alami dan nyaman"
  "Pasang Gorden Kain Sutra" = "menambah kemewahan dan kelembutan ruangan"
  "Pasang Gorden Kain Beludru" = "menciptakan kesan mewah dan berkelas"
  "Pasang Gorden Kain Rayon" = "melindungi dari sinar matahari dengan tampilan modern"
  "Pasang Gorden Kain Polyester" = "tahan lama dan mudah dirawat"
  "Pasang Gorden Kain Linen" = "memberikan tampilan alami dengan tekstur lembut"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Jasa Pasang dan Penjualan Gorden Berkualitas | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"